### ISSUE TITLE
example code does not work

### ISSUE THREAD

**Issue by grg2rsr** [larsrollik/pypulsepal#10]
the provided example code doesn't run on my system:

```
# Create PulsePal object
pp = PulsePal(serial_port=serial_port)

# Set parameters

## Manually
pp.program_one_param(channel=2, param_name="phase1Duration", param_value=.002)

## Via convencience functions
pp.set_resting_voltage(channel=2, voltage=4.2)

# Upload parameters
pp.upload_all()

# Trigger channels
pp.trigger_selected_channels(channel_2=True, channel_4=True)
pp.trigger_all_channels()

# Stop outputs
pp.stop_all_outputs()

# Save settings (also done automatically on disconnect)
pp.save_settings()
```

`trigger_all_channels()` calls `self.trigger_channels()` of the PulsePal object, which isn't implemented. Guessing by its call signature that it should be `self.trigger_selected_channels()` still makes it crash further down the road, briefly looking at it seems like `_read_confirmation()` never returns True.

Windows 10, PulsePal 2.0

**Comment by larsrollik** [comment]
Thank you for reporting this typo!

I will look into the issue with the examples. For now, I have separated them out for all vs selected channels and added some delays between trigger commands, because I suspect at the moment that the issue is in the serial communication.

See [9b07aff](https://github.com/larsrollik/pypulsepal/commit/9b07aff8d0fec9d142d82c1ffd4bba3586c0e8ea).

**Comment by grg2rsr** [comment]
Hi, I remember ran into a similar issue using PulsePal3 from Sanworks, I needed to introduce some `time.sleep()` to have it I guess process uploaded code. But there also suffering from other issues so then I stumbled upon your library which looks great, thanks for coding it up :)
